### ISSUE TITLE
delete support

### ISSUE THREAD

**Issue by foolusion** [samsung-cnct/cma-ssh#98]
I was hoping to simplify delete by only using ownerReferences and having kubernetes do the clean up. I wrote the delete assuming we would use [foreground cascading delete](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion), but kubectl uses [background cascading delete](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#background-cascading-deletion). This means if you call delete on a cluster it deletes the cluster object then deletes all the dependent objects. I would like to use the foreground deletion which would set a finalizer on cluster object then delete all the children. once all dependent objects are deleted then the cluster is finally deleted. The choices are support kubectl or only support delete through kubernetes api. I lean more towards api since kubectl has other irregularities. What should we do?

**Comment by davidewatson** [comment]
Cluster API (CAPI) `Machines` also uses foreground deletion:

https://github.com/kubernetes-sigs/cluster-api/blob/abfd18620fd024a48e1a53db448527e871966f23/pkg/controller/machine/controller.go#L122

It's not clear to me why you can't support `kubectl` and use foreground deletion. Will anything "bad" happen except for `kubectl` blocking? If not, I think that's okay. A different UX can implement a different UX.

# References

https://github.com/kubernetes/kubernetes/issues/66110

**Comment by foolusion** [comment]
#102 fixed this
